### ISSUE TITLE
About icd10!

### ISSUE THREAD

**Issue by allenanie** [sirrice/icd9#5]
Hi @sirrice, 

This package is amazing!! Very easy to use and exactly what I was looking for -- I'm trying to map icd9 codes to actual disease names and also need to check if a certain code is a valid icd9 code! Thank you for creating and sharing this!

I'm trying to find a similar library for ICD10. After some search, I couldn't find one that's as easy as yours...do you have recommendations for which ICD10 python library to try?

**Comment by sirrice** [comment]
I'm sorry, I don't.  From a quick google search, I couldn't find a readily accessible ICD10 dataset.  I'd love a pull request for it.

**Comment by windweller** [comment]
What type of format do you need?

I know https://www.icd10data.com/ has been amazing to use (from an HTML point of view). Maybe it can be scrapped in some easy manner.

**Comment by allenanie** [comment]
OK :) I've been using this website for a while: https://www.icd10data.com/

If I have enough time I'll scrap it and save it into the JSON format you detailed in the README. Thanks for answering!
